### ISSUE TITLE
When there is a "No newline at end of file" in the diff, the suggestion-bot code review comment is truncated incorrectly.

### ISSUE THREAD

**Issue by LarryKiniu** [tido64/suggestion-bot#135]
When there is a "No newline at end of file" in the diff, the suggestion-bot code review comment is truncated incorrectly.
For instance, if this is the diff:
```
diff --git a/src/index.ts
index 3f8c7c6e0..59c31a76c 100644
--- a/src/index.ts
+++ b/index.ts
@@ -1 +1 @@
-export { default as EmployeesAlsoAsked } from "./EAAAccordion";
\ No newline at end of file
+export { default as EmployeesAlsoAsked } from "./EAAAccordion";
```
then the code review suggestion is truncated like this:
![suggestion-bot-comment](https://user-images.githubusercontent.com/919162/135988984-4f4d7f9e-cd36-467e-bf96-a1d546e4e815.png)

**Comment by tido64** [comment]
Resolved by #136
