### ISSUE TITLE
suggestion-bot reads from stdin when it's not a TTY, even if a diff file is specified

### ISSUE THREAD

**Issue by zygoloid** [tido64/suggestion-bot#430]
If stdin is not a TTY, suggestion-bot [reads from stdin](https://github.com/tido64/suggestion-bot/blob/48d42a39fdbf738f1e60f1a83f6c64b222c5ebff/cli.js#L72) regardless of whether a diff is specified on the command line. This means that, for example, the documented usage of putting

```
GITHUB_TOKEN=<secret> suggestion-bot "$(git diff)"
```

in a github action does not work. In a github action, stdin is never a TTY, so this reads an (empty) diff from stdin instead of reading the command-line diff. Moreover, no error or warning is emitted for the unused positional parameter in this case.

It also seems really weird to me that suggestion-bot would take a diff, rather than a filename of a diff file, as an argument.

Suggestion: produce an error if there are unused positional arguments.

Alternatively, I think the ideal thing to do would be to take a diff *filename* on the command line, and fall back to stdin only if no filename is provided. Hopefully that wouldn't break too many existing workflows, given that providing a diff on the command line doesn't work currently because in existing workflows stdin will generally not be a TTY.

**Comment by tido64** [comment]
Hi @zygoloid, thanks for filing this issue. I have submitted a fix. Let me know if you can try it out and see if it works for you.
